/* eslint-disable */
// Generated by Wrangler by running `wrangler types --config=wrangler.binance-browser.jsonc --include-runtime=false --env-interface=BinanceWorkerEnv workers/binance-worker-configuration.d.ts` (hash: 7bc10a9bece089cc02a4e814d69fbaad)
interface __BaseEnv_BinanceWorkerEnv {
	BROWSER: BrowserRun;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./binance-browser");
	}
	interface Env extends __BaseEnv_BinanceWorkerEnv {}
}
interface BinanceWorkerEnv extends __BaseEnv_BinanceWorkerEnv {}
