/* eslint-disable */
// Generated by Wrangler by running `wrangler types --config=wrangler.chinese-social-browser.jsonc --include-runtime=false --env-interface=ChineseSocialBrowserWorkerEnv workers/chinese-social-browser-configuration.d.ts` (hash: 8d1032aedad40f0d8e195fa6e6c25a3b)
interface __BaseEnv_ChineseSocialBrowserWorkerEnv {
	BROWSER: BrowserRun;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./chinese-social-browser");
	}
	interface Env extends __BaseEnv_ChineseSocialBrowserWorkerEnv {}
}
interface ChineseSocialBrowserWorkerEnv extends __BaseEnv_ChineseSocialBrowserWorkerEnv {}
