/* eslint-disable */
// Generated by Wrangler by running `wrangler types --config=wrangler.fulltext-browser.jsonc --include-runtime=false --env-interface=FulltextBrowserWorkerEnv workers/fulltext-browser-configuration.d.ts` (hash: 064862cccb69684760ab0bfa4e3b6586)
interface __BaseEnv_FulltextBrowserWorkerEnv {
	BROWSER: BrowserRun;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./fulltext-browser");
	}
	interface Env extends __BaseEnv_FulltextBrowserWorkerEnv {}
}
interface FulltextBrowserWorkerEnv extends __BaseEnv_FulltextBrowserWorkerEnv {}
